### ISSUE TITLE
time label on decadal mean files should be revised (it is misleading)

### ISSUE THREAD

**Issue by durack1** [cmip6dr/cmip7_forward_look#41]
See pcmdi/cmor#405 for discussion

@taylor13

**Comment by martinjuckes** [comment]
Closed .. see linked issue.

**Comment by durack1** [comment]
@martinjuckes, if it's helpful, you can migrate issues from one repo to another - moving some of these to a repo in the https://github.com/CMIP-Data-Request/ organization might be a good way to keep information together
